Repository Devilstation/imp-station-14, pull requests merged in 2025-08, with the labels that each got.

#19 Five. Hundred. Cyborgs.
  Resources/Prototypes/_Impstation/Maps/Eclipse.yml
  Resources/Prototypes/_Impstation/Maps/amber.yml
  Resources/Prototypes/_Impstation/Maps/anthill.yml
  Resources/Prototypes/_Impstation/Maps/bagel.yml
  Resources/Prototypes/_Impstation/Maps/banana.yml
  Resources/Prototypes/_Impstation/Maps/barratry.yml
  Resources/Prototypes/_Impstation/Maps/bedlam.yml
  Resources/Prototypes/_Impstation/Maps/boat.yml
  Resources/Prototypes/_Impstation/Maps/box.yml
  Resources/Prototypes/_Impstation/Maps/cog.yml
  Resources/Prototypes/_Impstation/Maps/core.yml
  Resources/Prototypes/_Impstation/Maps/elkridge.yml
  Resources/Prototypes/_Impstation/Maps/gate.yml
  Resources/Prototypes/_Impstation/Maps/hash.yml
  Resources/Prototypes/_Impstation/Maps/hummingbird.yml
  Resources/Prototypes/_Impstation/Maps/lilboat.yml
  Resources/Prototypes/_Impstation/Maps/luna.yml
  Resources/Prototypes/_Impstation/Maps/marathon.yml
  Resources/Prototypes/_Impstation/Maps/oasis.yml
  Resources/Prototypes/_Impstation/Maps/packed.yml
  Resources/Prototypes/_Impstation/Maps/plasma.yml
  Resources/Prototypes/_Impstation/Maps/refsdal.yml
  Resources/Prototypes/_Impstation/Maps/relic.yml
  Resources/Prototypes/_Impstation/Maps/saltern.yml
  Resources/Prototypes/_Impstation/Maps/skimmer.yml
  Resources/Prototypes/_Impstation/Maps/submarine.yml
  Resources/Prototypes/_Impstation/Maps/train.yml
  Resources/Prototypes/_Impstation/Maps/union.yml
  Resources/Prototypes/_Impstation/Maps/whisper.yml
  Resources/Prototypes/_Impstation/Maps/xeno.yml
Labels: S: Untriaged, size/S

#21 Sillycon minor QOL changes
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/base_pka.yml
Labels: S: Untriaged, size/S, S: Needs Review

#30 Minor Xenoborg changes
  Resources/Locale/en-US/datasets/names/xenoborg.ftl
  Resources/Locale/en-US/station-laws/laws.ftl
  Resources/Prototypes/Entities/Mobs/Cyborgs/xenoborgs.yml
  Resources/Prototypes/_hereelabs/Entities/Mobs/Cyborgs/xenoborgs.yml
Labels: size/M, S: Untriaged, S: Needs Review

#31 Add a few custom admeme jobs
  Resources/Locale/en-US/_hereelabs/departments.ftl
  Resources/Prototypes/_hereelabs/Roles/Jobs/Wildcards/angler.yml
  Resources/Prototypes/_hereelabs/Roles/Jobs/Wildcards/assistant.yml
  Resources/Prototypes/_hereelabs/Roles/Jobs/Wildcards/rancher.yml
  Resources/Prototypes/_hereelabs/Roles/Jobs/Wildcards/vicepresident.yml
  Resources/Prototypes/_hereelabs/Roles/Jobs/departments.yml
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie.rsi/folded-equipped-INNERCLOTHING.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie.rsi/icon.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie.rsi/inhand-left.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie.rsi/inhand-right.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie.rsi/meta.json
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie2.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie2.rsi/icon.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie2.rsi/inhand-left.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie2.rsi/inhand-right.png
  Resources/Textures/_hereelabs/Clothing/Uniforms/Jumpsuit/staffie2.rsi/meta.json
  Resources/Textures/_hereelabs/Interface/Misc/job_icons.rsi/Angler.png
  Resources/Textures/_hereelabs/Interface/Misc/job_icons.rsi/Mechanic.png
  Resources/Textures/_hereelabs/Interface/Misc/job_icons.rsi/Rancher.png
  Resources/Textures/_hereelabs/Interface/Misc/job_icons.rsi/StaffAssistant.png
  Resources/Textures/_hereelabs/Interface/Misc/job_icons.rsi/VicePresident.png
  Resources/Textures/_hereelabs/Interface/Misc/job_icons.rsi/meta.json
  Resources/Textures/_hereelabs/Objects/Misc/id_cards.rsi/default.png
  Resources/Textures/_hereelabs/Objects/Misc/id_cards.rsi/idangler.png
  Resources/Textures/_hereelabs/Objects/Misc/id_cards.rsi/idassistant.png
  Resources/Textures/_hereelabs/Objects/Misc/id_cards.rsi/idrancher.png
  Resources/Textures/_hereelabs/Objects/Misc/id_cards.rsi/idvicepresident.png
  Resources/Textures/_hereelabs/Objects/Misc/id_cards.rsi/meta.json
  Resources/Textures/_hereelabs/Objects/Misc/id_cards.rsi/weatheredgold.png
Labels: S: Untriaged, S: Needs Review, Changes: Sprites, Changes: No C#, Changes: Port
