Repository Devilstation/imp-station-14, pull requests merged in 2025-09, with the labels that each got.

#68 he's stronger.
  Resources/Prototypes/_hereelabs/Entities/Mobs/Admeme/machoman.yml
Labels: Changes: No C#, Changes: Port

#66 Shadow+Flesh Anomaly rework.
  Content.Server/_Lavaland/Tendril/Components/TendrilComponent.cs
  Content.Server/_Lavaland/Tendril/Components/TendrilMobComponent.cs
  Content.Server/_Lavaland/Tendril/TendrilMobDeadEvent.cs
  Content.Server/_Lavaland/Tendril/TendrilSystem.cs
  Content.Shared/Anomaly/Components/AnomalySupercriticalComponent.cs
  Resources/Audio/Ambience/attributions.yml
  Resources/Audio/Ambience/wisp_ambience.ogg
  Resources/Audio/_DV/Glimmer_Creatures/attributions.yml
  Resources/Audio/_DV/Glimmer_Creatures/mite.ogg
  Resources/Audio/_RMC14/Xeno/alien_echoroar_1.ogg
  Resources/Locale/en-US/_Lavaland/salvage/tendril.ftl
  Resources/Prototypes/Entities/Mobs/NPCs/glimmer_creatures.yml
  Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomalies.yml
  Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/demons.yml
  Resources/Prototypes/_Goobstation/Entities/Structures/Specific/fleshgate.yml
  Resources/Prototypes/_Lavaland/Catalog/Fills/Crates/necropolis.yml
  Resources/Prototypes/_Lavaland/Entities/Markers/Spawners/Random/crates.yml
  Resources/Prototypes/_Lavaland/Entities/Markers/Spawners/Random/tendril.yml
  Resources/Prototypes/_Lavaland/Entities/Structures/Specific/tendril.yml
  Resources/Prototypes/_Lavaland/Entities/Structures/Storage/Crates/necropolis.yml
  Resources/Textures/Mobs/Demons/glimmer_wisp.rsi/meta.json
  Resources/Textures/Mobs/Demons/glimmer_wisp.rsi/willowisp.png
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/magic.png
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/magic_base.png
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/magic_flare.png
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/meta.json
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/miner.png
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/miner_base.png
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/miner_flare.png
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/tech.png
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/tech_base.png
  Resources/Textures/_DV/Mobs/Aliens/Guardians/guardians.rsi/tech_flare.png
  Resources/Textures/_DV/Mobs/Ghosts/glimmermite.rsi/icon.png
  Resources/Textures/_DV/Mobs/Ghosts/glimmermite.rsi/meta.json
  Resources/Textures/_DV/Mobs/Ghosts/glimmermite.rsi/mite.png
  Resources/Textures/_DV/Mobs/Ghosts/glimmermite.rsi/mite_dead.png
  Resources/Textures/_Goobstation/Mobs/Aliens/flesh.rsi/alive.png
  Resources/Textures/_Goobstation/Mobs/Aliens/flesh.rsi/dead.png
  Resources/Textures/_Goobstation/Mobs/Aliens/flesh.rsi/meta.json
  Resources/Textures/_Goobstation/Structures/Specific/fleshgate.rsi/fleshgate.png
  Resources/Textures/_Goobstation/Structures/Specific/fleshgate.rsi/meta.json
  Resources/Textures/_Lavaland/Structures/Specific/tendril.rsi/meta.json
  Resources/Textures/_Lavaland/Structures/Specific/tendril.rsi/tendril.png
  Resources/Textures/_Lavaland/Structures/Storage/Crates/necropolechest.rsi/base.png
  Resources/Textures/_Lavaland/Structures/Storage/Crates/necropolechest.rsi/closed.png
  Resources/Textures/_Lavaland/Structures/Storage/Crates/necropolechest.rsi/icon.png
  Resources/Textures/_Lavaland/Structures/Storage/Crates/necropolechest.rsi/meta.json
  Resources/Textures/_Lavaland/Structures/Storage/Crates/necropolechest.rsi/open.png
  Resources/Textures/_Lavaland/Structures/Storage/Crates/necropolechest.rsi/welded.png
Labels: Changes: Sprites, Changes: Port, Changes: Upstream, Changes: Audio

#71 ERT Cyborgs are here!
  Resources/Locale/en-US/station-laws/laws.ftl
  Resources/Prototypes/_hereelabs/Entities/Mobs/Admeme/machoman.yml
  Resources/Prototypes/_hereelabs/Entities/Mobs/Admeme/spacejesus.yml
  Resources/Prototypes/_hereelabs/Entities/Mobs/Cyborgs/borg_chassis.yml
  Resources/Prototypes/_hereelabs/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/_hereelabs/Entities/Objects/Weapons/Melee/security.yml
  Resources/Prototypes/silicon-laws.yml
  Resources/Prototypes/tags.yml
  Resources/Textures/Interface/Actions/actions_borg.rsi/ert-module.png
  Resources/Textures/Interface/Actions/actions_borg.rsi/meta.json
  Resources/Textures/Mobs/Silicon/chassis.rsi/ERT.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/ERT_e.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/ERT_e_r.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/ERT_l.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/meta.json
  Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/centcomm.png
  Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/icon-ert.png
  Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/meta.json
Labels: Changes: Sprites, Changes: No C#, Changes: Port, Changes: Upstream

#74 || TARGET.AQUIRED || (Deathsquad Cyborgs)
  Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
  Resources/Prototypes/Roles/Jobs/CentComm/deathsquad.yml
  Resources/Prototypes/_hereelabs/Entities/Mobs/Cyborgs/borg_chassis.yml
  Resources/Prototypes/_hereelabs/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/_hereelabs/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/_hereelabs/Entities/Objects/Weapons/Melee/e_sword.yml
  Resources/Prototypes/_hereelabs/Entities/Objects/Weapons/Melee/mining.yml
  Resources/Textures/Mobs/Silicon/chassis.rsi/commando.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/commando_e.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/commando_e_r.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/commando_l.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/meta.json
  Resources/Textures/_hereelabs/Objects/Tools/sonicjackhammer.rsi/inhand-left.png
  Resources/Textures/_hereelabs/Objects/Tools/sonicjackhammer.rsi/inhand-right.png
  Resources/Textures/_hereelabs/Objects/Tools/sonicjackhammer.rsi/meta.json
  Resources/Textures/_hereelabs/Objects/Tools/sonicjackhammer.rsi/sonicjackhammer.png
Labels: Changes: Sprites, Changes: No C#, Changes: Port, Changes: Upstream

#80 Update Admeme & Expand RCD building options
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
  Resources/Prototypes/Entities/Structures/Machines/silo.yml
  Resources/Prototypes/RCD/rcd.yml
  Resources/Prototypes/_hereelabs/Entities/Mobs/Admeme/STRIDER-2.yml
  Resources/Textures/Interface/Radial/RCD/Norm_door.png
  Resources/Textures/Interface/Radial/RCD/WMGen_static.png
  Resources/Textures/Interface/Radial/RCD/Xeno_door.png
  Resources/Textures/Interface/Radial/RCD/firelock_glass.png
  Resources/Textures/Interface/Radial/RCD/sec_windoor.png
  Resources/Textures/Interface/Radial/RCD/static.png
  Resources/Textures/Interface/Radial/RCD/substation_static.png
Labels: Changes: No C#, Changes: Port, Changes: Upstream

#81 Even more xenoborg stuff
  Resources/Audio/_Goobstation/Flock/Flock_Reactor.ogg
  Resources/Audio/_Goobstation/Flock/flock_broadcast_charge.ogg
  Resources/Audio/_Goobstation/Flock/flock_broadcast_kaboom.ogg
  Resources/Locale/en-US/_hereelabs/alert-levels/alert-levels.ftl
  Resources/Locale/en-US/_hereelabs/contraband/contraband-severity.ftl
  Resources/Prototypes/AlertLevels/alert_levels.yml
  Resources/Prototypes/Entities/Objects/base_contraband.yml
  Resources/Prototypes/_Goobstation/Flock/Machines/featherzone.yml
  Resources/Prototypes/_Impstation/Entities/Mobs/Player/Silicon/Replicators/replicator-damage.yml
  Resources/Prototypes/_Impstation/Entities/Mobs/Player/Silicon/Replicators/replicator-loadout.yml
  Resources/Prototypes/_Impstation/Entities/Mobs/Player/Silicon/Replicators/replicator-nest.yml
  Resources/Prototypes/_Impstation/Entities/Mobs/Player/Silicon/Replicators/replicators.yml
  Resources/Prototypes/_hereelabs/Entities/Mobs/Cyborgs/xenoborgs.yml
  Resources/Prototypes/_hereelabs/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/_hereelabs/Entities/Objects/Weapons/Throwable/grenades.yml
  Resources/Prototypes/_hereelabs/contraband_severities.yml
  Resources/ServerInfo/_Impstation/Guidebook/AlertProcedure.xml
  Resources/Textures/Mobs/Silicon/chassis.rsi/meta.json
  Resources/Textures/Mobs/Silicon/chassis.rsi/xenoborg_bomber.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/xenoborg_bomber_e.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/xenoborg_bomber_e_r.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/xenoborg_bomber_l.png
  Resources/Textures/Mobs/Silicon/chassis.rsi/xenoborg_bomber_moving.png
  Resources/Textures/_Goobstation/Flock/Structures/160x160/reactor.rsi/meta.json
  Resources/Textures/_Goobstation/Flock/Structures/160x160/reactor.rsi/reactor_effect.png
  Resources/Textures/_Goobstation/Flock/Structures/160x160/reactor.rsi/reactor_off.png
  Resources/Textures/_Goobstation/Flock/Structures/160x160/reactor.rsi/reactor_on.png
Labels: Changes: Sprites, Changes: No C#, Changes: Port, Changes: Upstream, Changes: Audio, Changes: Guidebook

#83 Whoops i missed something. [Fix base RCD's]
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
Labels: Changes: No C#, Changes: Upstream
